CREATE DATABASE booklibrary;
CREATE USER booklibrary WITH ENCRYPTED PASSWORD 'Qwerty12';
GRANT ALL PRIVILEGES ON DATABASE booklibrary TO booklibrary;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO booklibrary;